### ISSUE TITLE
stratergy='mobile' is returning desktop results

### ISSUE THREAD

**Issue by dibg** [prakhargurunani/PyPSI#1]
i execute this:
mobile = PSI(url=URL, category='performance', locale='en',  stratergy='mobile', api_key=API_KEY)

and in the json i see that i get the desktop result:
{'emulatedFormFactor': 'desktop', 'formFactor': 'desktop', 'locale': 'en', 'onlyCategories': ['performance'], 'channel': 'lr'}

I also verified the numbers, i sloud have scored much less in the mobile test

**Comment by FirePing32** [comment]
This is now fixed in [`v1.9.1`(release)](https://github.com/FirePing32/PyPSI/releases/tag/v1.9.1).
