### ISSUE TITLE
More details if request fails?

### ISSUE THREAD

**Issue by rutgersmit** [prakhargurunani/PyPSI#2]
Hi,

The current version does not give that much information when a request fails. The only I get with str(ex) is 'lighthouseResult'. 
The API does give much more information in the 'message' attribute. 

It would be nice if that error message is available in the exception. Is that possible?

`{
    "error": {
        "code": 500,
        "message": "Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)",
        "errors": [
            {
                "message": "Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)",
                "domain": "lighthouse",
                "reason": "lighthouseError"
            }
        ]
    }
}`

**Comment by FirePing32** [comment]
Did you try using the [official tool](https://developers.google.com/speed/pagespeed/insights) ? Does it give any errors ?

**Comment by rutgersmit** [comment]
The error I posted is an example, just entered some non-existing url. 
Sometimes a request fails and the only information I get from the package is 'lighthouseResult', and not the descriptive error message witch the API returns.

**Comment by FirePing32** [comment]
Yeah. The tool lacks this reporting right now. I am not actively maintaining the project. Can you work on this feature ? Or else you will have to wait for some time for getting proper error reporting in the next version.

**Comment by rutgersmit** [comment]
My Python skills are pretty fresh. Maybe I'll give it a shot if I have some spare time available.
Thanks
