### ISSUE TITLE
Setup Error Reporting

### ISSUE THREAD

**Issue by FirePing32** [prakhargurunani/PyPSI#3]
The current version does not give that much information when a request fails. The API does give much more information in the 'message' attribute.

It would be nice if that error message is available in the exception. 

Ref: #2

**Comment by ibrahimsha23** [comment]
@FirePing32  May I work on this?

**Comment by FirePing32** [comment]
@ibrahimsha23 Sure !

**Comment by ibrahimsha23** [comment]
@FirePing32 Thanks,

 I would like to know, in local setup how will you be running the applications? Am facing some issues in my local , and I need to cross verify with you.
 
 example:
 by defining the main method(entry method) in api.py file.
 
 ```
 python ./api.py
 ```

**Comment by FirePing32** [comment]
Just run:
`python setup.py develop`

This way you can install and use PyPSI in development mode and debugging will be easier.

**Comment by ibrahimsha23** [comment]
@FirePing32  Thanks, the above suggestions it helped me out.

I have tried hitting non-existent URLs, using [google page speed apis](https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://ibrahimshak.com&key=) and PyPSI. Both the responses, look the same.  Do I need to add more custom messages on exception? could you please give me a brief on what needs to be done?

**Reference**:
1. PyPSI api response:
```
{'error': {'code': 500, 'message': 'Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)', 'errors': [{'message': 'Lighthouse returned error: FAILED_DOCUMENT_REQUEST. Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Details: net::ERR_CONNECTION_FAILED)', 'domain': 'lighthouse', 'reason': 'lighthouseError'}]}}
```
2. google api response.
<img width="1299" alt="Screenshot 2021-09-03 at 7 55 29 AM" src="https://user-images.githubusercontent.com/7839955/131941315-b56f3304-33d1-4be9-83e5-04d1c84d891b.png">

**Comment by FirePing32** [comment]
See #2.

**Comment by ghost** [comment]
This is still open on gitpay
